[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[functions]
  directory = "client/netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = ".netlify/functions/:splat"
  status = 200