[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions"

[functions]
  directory = "client/netlify/functions" # Path to your functions directory

[[redirects]]
  from = "/.netlify/functions/*"
  to = ".netlify/functions/:splat"
  status = 200