[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions/tindart-api"

[[redirects]]
  from = "/.netlify/functions/tindart-api/*"
  to = "/netlify/functions/tindart-api/:splat"
  status = 200